Spring:
  application:
    name: cazait

  # h2 Setting Information
  h2:
    console:
      enabled: true
      path: /h2-console

  # DataBase Setting Information
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/cazait;NON_KEYWORDS=USER
    hikari:
      username: sa
      password:

  sql:
    init:
      mode: always
      data-locations: classpath:h2/data.sql

  # JPA Setting Information
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true