Spring:
  application:
    name: cazait

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/cazait
    hikari:
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true