Server:
  port: 8082

Spring:
  config:
    activate:
      on-profile: local

  # h2 Setting Information
  h2:
    console:
      enabled: true
      path: /h2-console

  # DataBase Setting Information
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/cazait;NON_KEYWORDS=USER
    hikari:
      username: sa
      password:

  sql:
    init:
      mode: always
      data-locations: classpath:h2/data.sql

  # JPA Setting Information
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true