Server:
  port: 8080

Spring:
  profiles:
    active: local

  config:
    import: application-aws.yml

  application:
    name: cazait

  # JPA Setting Information
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true