Spring:
  application:
    name: cazait

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/cazait;NON_KEYWORDS=USER
    hikari:
      username: sa
      password:

    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true